version: '1.0'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # Map container's port 8000 to host's port 8000
    volumes:
      - ./budget.db:/app/budget.db # Persist the SQLite database file locally
    restart: unless-stopped