apiVersion: apps/v1
kind: Deployment
metadata:
  name: budget-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: budget-api
  template:
    metadata:
      labels:
        app: budget-api
    spec:
      containers:
      - name: budget-api
        image: budget-api:latest
        ports:
        - containerPort: 8000